#!/usr/bin/env python3
"""Regenerate a Finding from the rows it names. METHODOLOGY.md §7.4; RUBRIC.md gate 4.

    python tools/rebuild.py fn:sg:stock-act-ptr-after-deadline:v1:fl:house-clerk:P:20024346
    python tools/rebuild.py            # every Signal file, regenerated and compared

With a Finding's id, it hands the Signal only what the Finding names (the filing, that
filing's transactions, and the officeholder), regenerates the Finding, prints it, and
says whether it is the sealed row, byte for byte, apart from the two fields a build gives
a Finding once (fired_at, build_hash). With no id, it regenerates every file the Signals
write and compares each with the tree, which is the gate CI runs. A Finding of an earlier
version of a Signal is regenerated by checking out the commit that sealed it. Standard
library; it reads and never writes.
"""

from __future__ import annotations

import argparse
import importlib.util
import json
import sys
from pathlib import Path


def load(path: Path, name: str):
    spec = importlib.util.spec_from_file_location(name, path)
    module = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(module)
    return module


def one(root: Path, run, finding_id: str) -> int:
    ledger = {row["id"]: row for row in run.read_ndjson(root / run.FINDINGS)}
    sealed = ledger.get(finding_id)
    if sealed is None:
        print(f"FAIL  no Finding {finding_id} in {run.FINDINGS}")
        return 1
    base = run.CORRECTION.sub("", finding_id)
    slug = sealed["signal_id"].split(":")[1]
    definition = run.parse_definition(root / run.DEFINITIONS / f"{slug}.md")
    if definition["id"] != sealed["signal_id"]:
        print(
            f"FAIL  {finding_id} is a Finding of {sealed['signal_id']}; the current definition is "
            f"{definition['id']}. Check out the commit that sealed it and run this there."
        )
        return 1
    module = run.load_signal(root, slug)
    filings = [
        row
        for row in run.read_ndjson(root / run.INPUTS["filing"])
        if row["id"] in sealed["producing_filings"]
    ]
    transactions = [
        row
        for row in run.read_ndjson(root / run.INPUTS["transaction"])
        if row["filing_id"] in sealed["producing_filings"]
    ]
    holders = [
        row
        for row in run.read_ndjson(root / run.INPUTS["officeholder"])
        if row["id"] == sealed["officeholder_id"]
    ]
    findings, _ = module.evaluate(holders, filings, transactions)
    again = next((f for f in findings if f["id"] == base), None)
    if again is None:
        print(f"FAIL  the rows {finding_id} names no longer produce it")
        if sealed.get("superseded_by"):
            print(
                f"      It is superseded by {sealed['superseded_by']}: a correction moved the rows "
                "it was produced from, so it regenerates from the rows as they stood at the "
                "commit that sealed it (git log -- data/findings.ndjson), not from today's; "
                "the row that supersedes it regenerates from today's."
            )
        return 1
    regenerated = {**again, **{k: sealed[k] for k in run.PROVENANCE}}
    if base != finding_id:
        regenerated.update(id=sealed["id"], notes=sealed.get("notes"))
    print(json.dumps(regenerated, indent=2, sort_keys=True, ensure_ascii=False))
    if run.comparable(again) != run.comparable(sealed):
        print(f"\nFAIL  regenerated from {len(transactions)} rows; it differs from the sealed row")
        return 1
    print(
        f"\nOK    regenerated from the {len(transactions)} rows of "
        f"{', '.join(sealed['producing_filings'])}; "
        "identical to the sealed row."
    )
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument(
        "targets", nargs="*", help="a Finding id (fn:...), a repository root, or both"
    )
    args = parser.parse_args(argv)
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")
    ids = [t for t in args.targets if t.startswith("fn:")]
    roots = [t for t in args.targets if not t.startswith("fn:")]
    root = Path(roots[0] if roots else ".").resolve()
    run = load(root / "src" / "signals" / "run.py", "signals_run")
    if not ids:
        return run.main([str(root), "--check"])
    return max(one(root, run, finding_id) for finding_id in ids)


if __name__ == "__main__":
    sys.exit(main())
